### ISSUE TITLE
"RenderDocLoaderPlugin could not be found"

### ISSUE THREAD

**Issue by wip-** [Temaran/UE4RenderDocPlugin#1]
Hi,

I installed RenderDocPlugin by copying the content of the repo into my Project/Plugins/ folder.
When trying to open my project from UnrealEngineLauncher, I get the following message box:

"Question"
"Project modules are missing or out of date. Would you like to recompile them?"

I click "Yes", and get the following message box:

"Unreal Engine"
"Project is out of date, recompiling"

The message box quickly disappears, and is replaced by this next one:
"Game code couldn't be compiled. Continue trying to start anyway?"

I click "Yes", and finally get this error message:

"Message"
"Plugin 'RenderDocLoaderPlugin' failed to load because the module 'RenderDocLoaderPlugin' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project."

Then the only choice I have is to click "Ok" (doing so my project is not opened).
I am using UE4.4.3 with the revision 50046ec of UE4RenderDocPlugin, and have RenderDoc v0.20 installed.
Is there something I could try to improve the situation ?

Thank you.

**Comment by BenjaminDSmithy** [comment]
Hi @wip-,
What you need to do is follow these steps below:

## Setting up your project

**Windows:**
1. Be sure to have [Visual Studio 2013](http://www.microsoftstore.com/store/msusa/en_US/pdp/productID.284832100) installed.  You can use any desktop version of **Visual Studio 2013**, including the **free version:**  [Visual Studio 2013 Express for Windows Desktop](http://www.microsoft.com/en-us/download/details.aspx?id=40787).
2. Right click on **YourProject.uproject** to generate C++ project files.
3. You can now open up **YourProject.uproject** in the editor!
   - **NOTE:** If **YouProject.uproject** still fails to launch in the editor, open the **YouProject.sln** Microsoft Visual Studio Solution, **press F7** to build the solution & then **repeat step 3** after the build has completed.

I tend to find that using the UE4 "Project modules are missing or out of date. Would you like to recompile them?" seems to be a bit of a hit and a miss depending on whether you have your VS2013 IDE setup correctly with the engine or not.

Anyway,
I hope this helps :grinning: 

Cheers,
Benjamin

**Comment by Temaran** [comment]
Wip, are you still experiencing problems, or did Benjamin's answer solve your problem?

I've heard that some people are interested in using this for blueprint projects, unfortunately that is something that is currently not supported, could this be your situation?

I'm going to try and improve documentation and get 4.5 up and running as soon as I can get some free time :D

And I'm sorry for the late participation, I'm currently out of the country with very unreliable internet access :(

**Comment by wip-** [comment]
@Temaran I tried what Benjamin suggested, however it did not solve my problem.
When I try to open up the .uproject file in the Editor (step 3 above), I get a crash report that looks like what I copied below.
Now that I take a further look about it, it seems the error happens [here](https://github.com/Temaran/UE4RenderDocPlugin/blob/master/RenderDocPlugin/Source/RenderDocPlugin/Private/RenderDocPluginModule.cpp#L244).

In the end I resolved to using the standalone version of RenderDoc on the packaged version of my project, as I workaround, so the issue is may be not a priority.

---

Unknown exception - code 00000001 (first/second chance not available)

Assertion failed: OutTarget [File:C:\Users\wip\Documents\Unreal Projects\MyProject\Plugins\RenderDocPlugin\Source\RenderDocPlugin\Private\RenderDocPluginModule.cpp] [Line: 244]

KERNELBASE + 37901 bytes
UE4Editor_Core + 3095292 bytes
UE4Editor_Core + 1661738 bytes
UE4Editor_Core + 1541824 bytes
UE4Editor_RenderDocPlugin!FRenderDocPluginModule::StartupModule() + 403 bytes [c:\users\wip\documents\unreal projects\myProject\plugins\renderdocplugin\source\renderdocplugin\private\renderdocpluginmodule.cpp:55]
UE4Editor_Core + 2175035 bytes
UE4Editor_Projects + 77027 bytes
UE4Editor_Projects + 75178 bytes
UE4Editor!FEngineLoop::LoadStartupModules() + 92 bytes [d:\buildfarm\buildmachine_++depot+ue4-releases+4.4\engine\source\runtime\launch\private\launchengineloop.cpp:1772]
UE4Editor!FEngineLoop::PreInit() + 10981 bytes [d:\buildfarm\buildmachine_++depot+ue4-releases+4.4\engine\source\runtime\launch\private\launchengineloop.cpp:1329]
UE4Editor!GuardedMain() + 236 bytes [d:\buildfarm\buildmachine_++depot+ue4-releases+4.4\engine\source\runtime\launch\private\launch.cpp:112]
UE4Editor!GuardedMainWrapper() + 26 bytes [d:\buildfarm\buildmachine_++depot+ue4-releases+4.4\engine\source\runtime\launch\private\windows\launchwindows.cpp:125]
UE4Editor!WinMain() + 249 bytes [d:\buildfarm\buildmachine_++depot+ue4-releases+4.4\engine\source\runtime\launch\private\windows\launchwindows.cpp:201]
UE4Editor!__tmainCRTStartup() + 329 bytes [f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c:618]

**Comment by Temaran** [comment]
Hello there!

I'm now back home and I've looked a bit at the problem, but I'm not sure what it could be yet as I cannot repro it. I've gotten two new computers though, so I'm going to try and repro on those as well, otherwise I'm afraid I'm a bit stuck.

/Temaran
