### ISSUE TITLE
plugin missing or incompatible

### ISSUE THREAD

**Issue by chena1982** [Temaran/UE4RenderDocPlugin#12]
my ue4 is 4.10 x64, i use the portable renderdoc 2.06 x64, when i start the editor, it prompted that:"plugin missing or incompatible, missing or incompatible modules in renderdocloaderplugin plugin - would you like to disable it?"

i see this in the main page

> This plugin is known to work with UE4 up to version 4.10.1

which does i need to check?
thanks.

**Comment by Temaran** [comment]
Hmm, I can't be sure, check the date on the update of the readme.md in my
repo and try to pick the latest renderdoc version from that date.

I will try to update everything to work with the latest versions when I get
the time :)

/Temaran

2016-01-20 7:54 GMT+01:00 chena1982 notifications@github.com:
