### ISSUE TITLE
Keyboard shortcut no longer works

### ISSUE THREAD

**Issue by slomp** [Temaran/UE4RenderDocPlugin#20]
I am afraid I have inadvertently broken the frame capture keyboard shortcut [Alt+F12] while redesigning the viewport UI controls...

I am not entirely sure as to why it is no longer working, and frankly, the whole UE4 SlateUI is a huge pile of "not fun".

Any ideas as to why it stopped working?

PS: Sorry to bother you with this since I am the one that broke it, but I am out of ideas =/
It must something really stupid that I am overlooking, and a second opinion might help clarifying the problem.

**Comment by Temaran** [comment]
I'll see if I can't have a look in the weekend :D

2016-10-06 3:49 GMT+02:00 Marcos Paulo Berteli Slomp <
notifications@github.com>:

**Comment by Temaran** [comment]
Completely forgot about this issue, I looked at it shortly after though and it was because the code was generated further in the engine, I readded it in the pull request
