### ISSUE TITLE
RenderDoc plugin conflicts with Visual Studio Graphics Debugger

### ISSUE THREAD

**Issue by lifeisforu** [Temaran/UE4RenderDocPlugin#22]
If RenderDoc plugin is enabled, Visual Studio Graphics Debugger occurs error.

CreateSwapChain() call fails.

**Comment by Temaran** [comment]
Hello there!

Due to the nature of how graphics debuggers hook low level functions to collect data, this is unfortunately kind of expected.

I suggest only having one graphical debugging software active at one time.

Best regards,
/Temaran

**Comment by lifeisforu** [comment]
I understood. Thanks for your reply.  Have a nice day.
