### ISSUE TITLE
Crash on opening rendertarget asset

### ISSUE THREAD

**Issue by moradin** [Temaran/UE4RenderDocPlugin#23]
It crashes with the following callstack:

>  	renderdoc.dll!D3D11RenderState::ResourceRange::ResourceRange(ID3D11RenderTargetView * rtv) Line 1847	C++
 	renderdoc.dll!D3D11RenderState::UnbindIUnknownForWrite(const D3D11RenderState::ResourceRange & range) Line 1079	C++
 	renderdoc.dll!D3D11RenderState::UnbindForWrite<ID3D11RenderTargetView>(ID3D11RenderTargetView * rtv) Line 363	C++
 	renderdoc.dll!D3D11RenderState::ChangeRefWrite<ID3D11RenderTargetView>(ID3D11RenderTargetView * * stateArray, ID3D11RenderTargetView * const * newArray, unsigned __int64 offset, unsigned __int64 num) Line 431	C++
	renderdoc.dll!WrappedID3D11DeviceContext::OMSetRenderTargets(unsigned int NumViews, ID3D11RenderTargetView * const * ppRenderTargetViews, ID3D11DepthStencilView * pDepthStencilView) Line 3190	C++
 	UE4Editor-D3D11RHI.dll!FD3D11DynamicRHI::CommitRenderTargetsAndUAVs() Line 778	C++
 	UE4Editor-D3D11RHI.dll!FD3D11DynamicRHI::RHISetRenderTargets(unsigned int NewNumSimultaneousRenderTargets, const FRHIRenderTargetView * NewRenderTargetsRHI, const FRHIDepthRenderTargetView * NewDepthStencilTargetRHI, unsigned int NewNumUAVs, FRHIUnorderedAccessView * const * UAVs) Line 1042	C++
 	UE4Editor-Engine.dll!SetRenderTarget(FRHICommandList & RHICmdList, FRHITexture * NewRenderTarget, FRHITexture * NewDepthStencilTarget, bool bWritableBarrier) Line 280	C++
 	UE4Editor-Engine.dll!FSceneViewport::BeginRenderFrame(FRHICommandListImmediate & RHICmdList) Line 1468	C++
 	UE4Editor-Engine.dll!TGraphTask<`FViewport::EnqueueBeginRenderFrame'::`2'::EURCMacro_BeginDrawingCommand>::ExecuteTask(TArray<FBaseGraphTask *,FDefaultAllocator> & NewTasks, ENamedThreads::Type CurrentThread) Line 868	C++
 	UE4Editor-Core.dll!FNamedTaskThread::ProcessTasksNamedThread(int QueueIndex, bool bAllowStall) Line 932	C++
 	UE4Editor-Core.dll!FNamedTaskThread::ProcessTasksUntilQuit(int QueueIndex) Line 679	C++
 	UE4Editor-RenderCore.dll!RenderingThreadMain(FEvent * TaskGraphBoundSyncEvent) Line 320	C++
 	UE4Editor-RenderCore.dll!FRenderingThread::Run() Line 471	C++
 	UE4Editor-Core.dll!FRunnableThreadWin::Run() Line 74	C++
 	UE4Editor-Core.dll!FRunnableThreadWin::GuardedRun() Line 23	C++

**Comment by baldurk** [comment]
This should be reported upstream, it's not really related to this plugin except by fluke.

From the callstack I wonder if it's caused by [the bug mentioned in this commit](https://github.com/baldurk/renderdoc/commit/801f47a31ae97fd891d8242b7265f9ab7e97efd9) ? If so you could try using a recent nightly, it's hopefully fixed.

**Comment by moradin** [comment]
You are right. Closing
