### ISSUE TITLE
ue4 4.18

### ISSUE THREAD

**Issue by bimbachi** [Temaran/UE4RenderDocPlugin#33]
Plugin is on, icon dose not show up in Editor window?

**Comment by Temaran** [comment]
Hello!

This plugin has been part of the main source code since 4.16, so I would
recommend simply enabling the engine integrated one instead :)

2018-02-16 13:49 GMT+01:00 bimbachi <notifications@github.com>:

**Comment by bimbachi** [comment]
That is a situation that I;m referring too.
Regards


From: Temaran
Sent: sobota, 17 lutego 2018 11:33
To: Temaran/UE4RenderDocPlugin
Cc: bimbachi; Author
Subject: [Spam] Re: [Temaran/UE4RenderDocPlugin] ue4 4.18 (#33)

Hello!

This plugin has been part of the main source code since 4.16, so I would
recommend simply enabling the engine integrated one instead :)

2018-02-16 13:49 GMT+01:00 bimbachi <notifications@github.com>:

**Comment by bimbachi** [comment]
Yes it is about built in plugin.
I fond this in the log:
<<UATHelper: Packaging (Windows (64-bit)):   LogInit: Display: RenderDocPlugin: Error: unable to initialize the plugin because no RenderDoc libray has been located.
UATHelper: Packaging (Windows (64-bit)):   LogInit: Display: LogSimplygon: Warning: Failed to initialize Simplygon. Error: -10005.>>


Sent from Mail for Windows 10

From: Temaran
Sent: sobota, 17 lutego 2018 11:33
To: Temaran/UE4RenderDocPlugin
Cc: bimbachi; Author
Subject: [Spam] Re: [Temaran/UE4RenderDocPlugin] ue4 4.18 (#33)

Hello!

This plugin has been part of the main source code since 4.16, so I would
recommend simply enabling the engine integrated one instead :)

2018-02-16 13:49 GMT+01:00 bimbachi <notifications@github.com>:

**Comment by Temaran** [comment]
It looks like you have not installed renderdoc.
Please download the latest version of RenderDoc from Baldurs homepage,
hopefully that will fix it.


/Temaran

2018-02-20 18:17 GMT+01:00 bimbachi <notifications@github.com>:

**Comment by bimbachi** [comment]
I thought that if plugin is on the list in app (installed through the Launcher) it means it has everything necessary to run?
also I had to switch off plugin because I couldn’t build game. 
Best regards

                    
Note: This message was sent via a iPhone handset

**Comment by Temaran** [comment]
No, the plugin still requires a Renderdoc installation, this is stated in
the instructions :)
The plugin simply loads renderdoc and makes it easier to generate captures
with the proper meta-data.

/Temaran

2018-02-21 12:24 GMT+01:00 bimbachi <notifications@github.com>:

**Comment by bimbachi** [comment]
Ok, thank you
                    
Note: This message was sent via a iPhone handset
